name       : binaryen
version    : '91'
release    : 2
source     :
    - https://github.com/WebAssembly/binaryen/archive/version_91.tar.gz : 522a30c0fd29f55d44dbc299aa768eccbda67ef134c8563085f874daa5622d7a
license    : Apache-2.0
homepage   : https://github.com/WebAssembly/binaryen
component  : programming
summary    : Compiler infrastructure and toolchain library for WebAssembly
description: |
    Binaryen is a compiler and toolchain infrastructure library for WebAssembly, written in C++
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00755 $pkgfiles/50-binaryen.sh $installdir/usr/share/defaults/etc/profile.d/50-binaryen.sh
