name       : binaryen
version    : '102'
release    : 7
source     :
    - https://github.com/WebAssembly/binaryen/archive/refs/tags/version_102.tar.gz : 6197a8d7220d1510bb0694a2984bfae4f8b38abd6bdf4c724551c831786992f6
license    : Apache-2.0
homepage   : https://github.com/WebAssembly/binaryen
component  : programming
summary    : Compiler infrastructure and toolchain library for WebAssembly
description: |
    Binaryen is a compiler and toolchain infrastructure library for WebAssembly, written in C++
setup      : |
    %patch -p1 < $pkgfiles/libbinaryen-soname.patch
    sed -i "s/bin\/wasm-opt test/bin\/wasm-opt ..\/test/g" CMakeLists.txt
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00755 $pkgfiles/50-binaryen.sh $installdir/usr/share/defaults/etc/profile.d/50-binaryen.sh
